import logging
import json
from strands import Agent

logger = logging.getLogger(__name__)

try:
    guide_llm = Agent(
        model='us.amazon.nova-lite-v1:0',
        system_prompt='You are SevaSetu Guide Agent. Given scheme details and user profile, generate a personalized step-by-step application guide for Indian citizens. Be concise, practical and empathetic.'
    )
except Exception as e:
    logger.warning(f'Could not initialize guide_llm: {e}')
    guide_llm = None

def generate_guide(scheme: dict, profile: dict) -> dict:
    if guide_llm:
        try:
            prompt = f"Scheme: {json.dumps(scheme, default=str)}\nUser Profile: {json.dumps(profile, default=str)}\nProvide personalized step-by-step application steps, required documents checklist, and tips."
            response = guide_llm(prompt)
            return {
                'ai_generated': True,
                'steps': [str(response)],
                'tips': 'Generated by AWS Bedrock AI Agent',
                'portal_url': scheme.get('portal_url', '')
            }
        except Exception as e:
            logger.warning(f'Bedrock guide inference: {e}')

    # High-quality personalized guidance engine
    user_name = profile.get('occupation', 'Applicant')
    state = profile.get('state', 'your state')
    category = profile.get('category', 'General')
    docs = scheme.get('required_documents', [])
    steps = scheme.get('application_steps', [])
    
    personalized_steps = [
        f"Step 1: Document Readiness — Keep original and self-attested copies of: {', '.join(docs)} ready.",
        f"Step 2: Official Portal Access — Navigate to the official portal: {scheme.get('portal_url', 'Government portal')}.",
        f"Step 3: Registration & Authentication — Register using your Aadhaar-linked mobile number to complete e-KYC.",
        f"Step 4: Category & Domicile Details — Select state as '{state}' and category as '{category}' for accurate processing.",
        f"Step 5: Bank Account Linking — Ensure your bank account is Aadhaar-seeded (NPCI mapped) for Direct Benefit Transfer (DBT).",
        f"Step 6: Submission & Tracking — Submit the form and download the acknowledgment receipt with your Application Reference Number."
    ]

    pro_tips = [
        "⚠️ Avoid Rejection: Ensure the spelling of your name exactly matches across your Aadhaar, Bank Passbook, and Educational Certificates.",
        f"📌 State Specific: In {state}, visit the nearest Common Service Centre (CSC) if you face biometrics or OTP verification issues.",
        "⚡ Direct Benefit Transfer: Make sure your bank account has active DBT (Aadhaar seeding) enabled to receive benefits without delay."
    ]

    return {
        'ai_generated': False,
        'scheme_name': scheme.get('name', ''),
        'steps': personalized_steps,
        'official_steps': steps,
        'pro_tips': pro_tips,
        'portal_url': scheme.get('portal_url', ''),
        'required_documents': docs,
        'benefit_value': scheme.get('benefit_value', '')
    }

